version: "3.9"

services:
  db:
    container_name: lens-db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: baloo
      POSTGRES_PASSWORD: junglebook
      POSTGRES_DB: lenslocked
    ports:
      - 5432:5432
