version: "3.9"

x-logging:
  &highlight-logging
    driver: fluentd
    options:
      fluentd-address: "otel.highlight.io:24224"
      fluentd-async: "true"
      fluentd-sub-second-precision: "true"
      tag: "<get from"

services:
  lenslocked:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ~/data/lenslocked.com/images:/app/images
    # This is for testing purposes.
    depends_on:
      - db
    logging: *highlight-logging

  caddy:
    image: caddy
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    logging: *highlight-logging

  db:
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ~/data/lenslocked.com/psql:/var/lib/postgresql/pgdata
    logging: *highlight-logging
