version: "3.9"

services:
  db:
    container_name: lens-db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${PSQL_USER}
      POSTGRES_PASSWORD: ${PSQL_PASSWORD} 
      POSTGRES_DB: ${PSQL_DATABASE}
